apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: "8.3.*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  targetNamespace: monitoring
  install:
    createNamespace: true
  values:
    image:
      repository: grafana/grafana-oss # Use <your-dockerhub-username>/grafana-custom if you built a custom image
      tag: latest
    service:
      type: LoadBalancer
      port: 3000
    persistence:
      enabled: true
      size: 1Gi
    adminUser: admin
    adminPassword: admin